### ISSUE TITLE
App not showing webcam view on screen

### ISSUE THREAD

**Issue by rojamelex** [sowbug/scanqr-app#1]
Hello @sowbug , I am trying to run this app for students on HP Chromebook 11 G4/G5 laptops on a public session, but only see a black screen instead of the computer webcam feed. Is there a fix for this? I also have this issue on my personal laptop HP Pavilion 15 cc6xx . We appreciate your help with this! The students would greatly benefit from using this application on their Chromebooks.

**Comment by sowbug** [comment]
Hi there,

This app is really old, and it's totally possible that it's rotted beyond repair. For the G5 laptops, according to [this document](https://www.chromium.org/chromium-os/chrome-os-systems-supporting-android-apps) you should be able to install Android apps, and [this newer article](https://www.laptopmag.com/articles/get-android-apps-on-your-chromebook) says they're available on HP 11 G4 as well. Will you please try [this QR code scanner app](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en_US) and see whether that works?

**Comment by rojamelex** [comment]
The QR app link you provided is not working, page redirect saying: "We're sorry, the requested URL was not found on this server."

**Comment by sowbug** [comment]
Weird. Try this one https://play.google.com/store/apps/details?id=com.srowen.bs.android.simple there are a zillion different barcode/QR code scanners on Play Store.

**Comment by killebrewj** [comment]
Hey sowbug,
This broke in Chrome 71 since createObjectURL was deprecated.

You can easily fix this in main.js on line 154 by replacing 

`video.src = window.URL.createObjectURL(stream);`

with

`try {
      video.srcObject = stream;
        } catch (error) {
          video.src = window.URL.createObjectURL(stream);
        }
`

Many teachers would love it if you could update your app. We use it heavily in our schools. 

Unfortunately Android apps are sometimes difficult to work with due to sandboxing and Chromebook hardware requirements for the Android app feature. I'm sure that's the long term solution but for now we're still reliant on a Chrome app.

Thanks!

edit - fixed a typo in the code

**Comment by sowbug** [comment]
Thank you very much for the patch. I applied it and confirmed it worked. I just updated [the item](https://chrome.google.com/webstore/detail/nihhbejdflkeingkkpakffdlmepaeaah/publish-delayed) in the Chrome Web Store, and if all goes well, then within 60 minutes it should be updated to version 0.0.4.0 containing your fix. You can press the "Update" button in chrome:extensions to update your local installation to that version.

Thanks again for your help, and I'm sorry it broke.
